### ISSUE TITLE
xref table error

### ISSUE THREAD

**Issue by BrightCodeStudio** [jurosh/php-pdf-merge#3]
Hi, How are you?
I have used your php-pdf-merge library on my project but I have some issues.
<p>Type: Exception</p>
<p>Message: Unexpected data in xref table</p>
<p>Filename: /pdfmerge/vendor/itbz/fpdi/src/pdf_parser.php</p>
<p>Line Number: 187</p>

Now this library is running on my localhost (windows) but it is not running on Linux server.
Could you help me now?

**Comment by jurosh** [comment]
Hey, am fine, thanks for report.

Hmm.. would be good to update pdf-merge library dependencies, error you are referencing is of `fpdi` external library - maybe it's fixed in newer version.

But sadly, I didn't worked on this library for a while (not even with PHP).. and I will not have time to make those changes in near future...

ps. all contributions are welcome!

**Comment by jurosh** [comment]
Also, did you tried to run code also on linux machine (or just VM), to know if it's something what's only related to Windows stack or general ?

**Comment by jurosh** [comment]
Also can you please paste here versions of PHP you are running - locally and on server
